import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const arahama = localFont({
  src: "./fonts/ara-hama-al-fida.ttf",
  display: "swap",
  variable: "--font-arahama",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${arahama.variable}`}>
      <body className="antialiased font-arahama">{children}</body>
    </html>
  );
}
